// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");
const TerserPlugin = require("terser-webpack-plugin");
const CopyPlugin = require("copy-webpack-plugin");


// Utilities.
const path = require( 'path' );
const glob = require( 'glob' );

// Add any a new entry point by extending the webpack config.
module.exports = {
    // mode: 'production',
	...defaultConfig,
    optimization: {
        minimizer: [
          // For webpack@5 you can use the `...` syntax to extend existing minimizers (i.e. `terser-webpack-plugin`), uncomment the next line
          // `...`,
          new CssMinimizerPlugin(),
        ],
        minimize: true,
        minimizer: [new TerserPlugin()],
      },
	...{
		entry: {
            //css
			      'css/theme': path.resolve( process.cwd(), 'src/scss', 'theme.scss' ),
            //js
            'js/submenu': path.resolve( process.cwd(), 'src/js', 'submenu.js' ),
            'js/mobile-nav': path.resolve( process.cwd(), 'src/js', 'mobile-nav.js' ),
            'js/product-details-image-carousel': path.resolve( process.cwd(), 'src/js', 'product-details-image-carousel.js' ),
            'js/nav-background-opacity': path.resolve( process.cwd(), 'src/js', 'nav-background-opacity.js' )
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} ),
            new CopyPlugin({
                patterns: [
                  { from: "assets/fonts", to: "assets/fonts" },
                ],
              }),
		]
	},
    stats: {
        errorDetails: true
    }
};